### ISSUE TITLE
Front page of CTF

### ISSUE THREAD

**Issue by amar-sharma** [nishantgandhi99/Anwesha-CTF#12]
Please check this mock up I have created for phase I and start making basic HTML structure first, we will take care of CSS later on. Also consult Bootstrap API for making HTML Structure.

![ctf homepage](https://cloud.githubusercontent.com/assets/4115406/5680271/e986870e-9830-11e4-9864-50755a402973.png)

**Comment by amar-sharma** [comment]
I'll assign it to Manvee and Rishita once they are contributor.

**Comment by nishantgandhi99** [comment]
done
